# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            <a href="https://www.epfl.ch">EPFL</a>
tagline:          Members' space
description:      Club Montagne
site_base:        https://clubmontagne.github.io/
url:              https://clubmontagne.github.io
baseurl:          /

author:
  name:           Hang Yuan
  url:            https://de.linkedin.com/pub/hang-calvin-yuan/56/464/ba4
  mail:           mailto:hang.yuan@epfl.ch
  
paginate:         1

# Custom vars
version:          

github:
  repo:           https://github.com/angerhang

google_analytics: UA-55002898-4
