# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hang Yuan
tagline:          Hang's space 
description:      Neuro@<a href="https://www.epfl.ch">EPFL</a> 2019
url:              http://angerhang.github.io
baseurl:          /

author:
  name:           Hang Yuan
  url:            https://de.linkedin.com/pub/hang-calvin-yuan/56/464/ba4
  mail:           mailto:hang.yuan@epfl.ch
  
paginate:         1

# Custom vars
version:          

github:
  repo:           https://github.com/angerhang

google_analytics: UA-55002898-4
